Task 1
GrigorevMS/JavaBSC pull request #1
Opened 2021-10-27 07:40 UTC by GrigorevMS

ToDoList. Task-1

2021-10-28 12:52 UTC, rinat-fatkhutdinov requested changes

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +        boolean Working = true;
по принятым правилам именования переменные начинаются с маленькой буквы

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +        Scanner in = new Scanner(System.in);
эти 3 переменные используются только внутри while - уменьшить область видимости()объявить там

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +        Task ToDo = new Task();
зачем? ещё ни одной задачи не создали, команд не было.

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +            System.out.print("ToDo List: ");
не информативное приглашение к вводу

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +        while(pos < input.length() && input.charAt(pos) == ' ') {
(повторяющийся кусок)

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +    private static String[] SepInput(String input) {
Реализовать используя готовые методы класса String(изучить и выбрать)

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +                    if(cmd_list[1].length() == 0) {
String.isEmpty() короче и легче читается

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +                    else if(!ToDo.SetDescription(cmd_list[1])) {
тут лучше проверить аргумент команды add, и только тогда создать задачу с описанием

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +    private boolean CheckInput (String input) {
по названию не понятен функционал

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +    Task(String description_input) {
не используется в коде

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +        Out = Out + Integer.toString(Id) + ") ";
вывод на печать не соответсвует ТЗ

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +        Out = Out + Integer.toString(Id) + ") ";
`Integer.toString` лишнее преобразование. при кокатенации со строкой, число автоматом приведётся к строке

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +            Out += "[v] ";
вывод на печать не соответсвует ТЗ

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +            Out += "[x] ";
вывод на печать не соответсвует ТЗ

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +            if(input.charAt(i) == '\n') {
не уверен, что можно ввести перевод строки. при нажатии <Enter> ввод завершается, нет?

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +        if(CheckInput(input)) {
проверку описания лучше вынести из этого класса

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +        if(CheckInput(input)) {
и возвращать boolean не надо будет

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +        return true;
тут тоже возвращать ничего не надо

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +        return true;
аналогично

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +    boolean SetId(int id){
метод не используется

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +    String GetDescription(){
метод не используется

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +    boolean GetStatus(){
метод не используется

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +    int GetId(){
метод не используется

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +        if(this.Status == false){
this не нужен

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +        if(this.Status == false){
status булево поле, его не надо проверять на равенство с false\true (в данном случае просто `!Status`)

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Task.java
> +        if(this.Status == false){
if-else лишний `Status = !Status`

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +                    if(!ToDo.SetStatus(false)) {
лишнее, false не возможен

2021-10-28 12:52 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +                        System.out.println(ToDo.Out());
нет вывода для команды print без аргумента

2021-10-30 10:31 UTC, GrigorevMS commented on Task-1/src/main/java/ToDoList/Main.java
> +        Scanner in = new Scanner(System.in);
Если я правильно понял, речь идет о переменных "in", "input_cmd" и "cmd_list", и если я помещу их объявление внутрь while, то они будут создаваться заново при каждой итерации цикла. Разве это не должно негативно отразиться на производительности? Или эта проблема решена на уровне компилятора?

2021-11-01 10:28 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +        Scanner in = new Scanner(System.in);
С `in` я погорячился :)
А вбивать в консоли команды быстрее, чем выделяется оперативная память вряд ли получится

2021-11-01 10:40 UTC, rinat-fatkhutdinov commented on Task-1/src/main/java/ToDoList/Main.java
> +        Scanner in = new Scanner(System.in);
А Scanner можно обернуть `try (Scanner in = new Scanner(System.in))`, чтоб закрывался

2021-11-10 13:09 UTC, GrigorevMS commented on Task-1/src/main/java/ToDoList/Main.java
> +        Task ToDo = new Task();
На мой взгляд это несколько упрощает код, так как если не инициализировать todo сразу, то придется в обработке каждой команды проверять существует ли уже хотя бы одна задача или нет, придется вводить еще одну boolean переменную, которая будет за это отвечать. Если же объявить ее сразу, то всего этого получается избежать, да и ресурсов эта инициализация отнимает немного

2021-11-10 14:51 UTC, GrigorevMS commented on Task-1/src/main/java/ToDoList/Task.java
> +    boolean SetId(int id){
Оставил все Set/Get методы для полей просто чтобы было в дальнейшем легче работать и не приходилось их дописывать когда они вдруг понадобятся

2021-11-10 14:56 UTC, GrigorevMS commented on Task-1/src/main/java/ToDoList/Main.java
> +        Task ToDo = new Task();
исправил это место

2021-11-10 14:57 UTC, GrigorevMS commented on Task-1/src/main/java/ToDoList/Main.java
> +                    else if(!ToDo.SetDescription(cmd_list[1])) {
исправлено вместе с преждевременной инициализацией todo

2021-11-10 14:58 UTC, closed without merging